[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tsurugi-udf-common"
version = "0.1.0"
description = "Common utilities"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["tsurugi_udf_common"]
