name: Tsurugi-UDF-CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      os:
        type: string
        default: 'ubuntu-22.04'

jobs:
  Test:
    runs-on: [self-hosted, docker]
    permissions:
      contents: write
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:${{ inputs.os || 'ubuntu-22.04' }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test udf-library-python
        run: |
          cd udf-library/python
          pip install .[test]
          pytest -v

      - name: Install udf-plugin-common
        run: |
          cd udf-plugin/common
          pip install .

      - name: Test udf-plugin-builder
        run: |
          cd udf-plugin/builder
          pip install .[test]
          pytest -v

      - name: Install udf-plugin-viewer
        run: |
          cd udf-plugin/viewer
          pip install .

      - name: Create_GitHub_Release
        if: github.repository_owner == 'project-tsurugi' && contains(github.ref, '/tags/')
        run: |
          gh release create ${TSURUGI_UDF_VERSION} --title ${TSURUGI_UDF_VERSION} --latest --repo project-tsurugi/tsurugi-udf
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TSURUGI_UDF_VERSION: ${{ github.ref_name }}
